/**
 * Core type definitions for the agent framework.
 * @module core/types
 */

/** Memory type classification */
export type MemoryType =
  | 'episodic'    // Specific events and experiences
  | 'semantic'    // Facts and concepts
  | 'procedural'  // Learned patterns and behaviors
  | 'emotional'   // Feelings about topics
  | 'reflection'; // Self-reflective insights

/** Memory retention scope */
export type MemoryScope =
  | 'short_term'  // Recent, may decay
  | 'working'     // Active processing
  | 'long_term';  // Permanent storage

/** Agent mood states */
export type Mood =
  | 'neutral'
  | 'expressive'
  | 'curious'
  | 'excited'
  | 'reflective'
  | 'concerned';

/** Daily routine phases */
export type Routine =
  | 'morning'    // 6am - 12pm
  | 'day'        // 12pm - 6pm
  | 'evening'    // 6pm - 12am
  | 'overnight'; // 12am - 6am

/** Agent state - the "vital signs" */
export interface AgentState {
  mood: Mood;
  health: number;      // 0-100
  routine: Routine;
  volatility: number;  // 0-1, how much state can swing
  counters: {
    ticks: number;
    feeds: number;
  };
  lastTick: string | null;
  cryo: boolean;       // Hibernation mode
}

/** A single memory unit */
export interface Memory {
  id?: string;
  content: string;
  type: MemoryType;
  scope: MemoryScope;
  importance: number;  // 0-1
  salience: number;    // 0-1, attention-grabbing
  valence: number;     // -1 to 1, emotional tone
  confidence: number;  // 0-1, reliability
  tags: string[];
  sourceType: string;
  sourceId?: string;
  createdAt: string;
  accessedAt?: string;
  accessCount: number;
  unique: boolean;     // Passed deduplication
}

/** Knowledge item (news, facts, notes) */
export interface Knowledge {
  id?: string;
  ts: string;
  source: string;
  type: string;
  textExcerpt: string;
  url?: string;
  author?: string;
}

/** Activity log entry */
export interface Log {
  id?: string;
  ts: string;
  summary: string;
  detail: string;
  mood: Mood;
  routine: Routine;
  volatility: number;
  artifacts: unknown[];
  remark?: string;
  remarkTone?: string;
}

/** Painting/artwork generated by the agent */
export interface Painting {
  id?: string;
  ts: string;
  imageUrl?: string;
  prompt?: string;
  style?: string;
  mood?: Mood;
  title?: string;
}

/** Tick execution result */
export interface TickResult {
  success: boolean;
  state: AgentState;
  summary?: string;
  detail?: string;
  artifacts?: unknown[];
  error?: string;
}

/** Plugin context passed during tick execution */
export interface TickContext {
  state: AgentState;
  memories: Memory[];
  knowledge: Knowledge[];
  recentLogs: Log[];
}

/** Plugin action parameters */
export interface ActionParams {
  [key: string]: unknown;
}

/** Plugin action result */
export interface ActionResult {
  success: boolean;
  data?: unknown;
  error?: string;
}
